# Generated by Django 2.2.5 on 2021-07-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20210701_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='position1',
        ),
        migrations.RemoveField(
            model_name='position',
            name='position2',
        ),
        migrations.RemoveField(
            model_name='position',
            name='position3',
        ),
        migrations.RemoveField(
            model_name='position',
            name='position4',
        ),
        migrations.RemoveField(
            model_name='position',
            name='position5',
        ),
        migrations.RemoveField(
            model_name='position',
            name='position6',
        ),
        migrations.AddField(
            model_name='position',
            name='position1_1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='position1_2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='position2_1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='position2_2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='position3_1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='position3_2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='position4_1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='position4_2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='position5_1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='position5_2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='position6_1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='position6_2',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
