# Generated by Django 2.2.5 on 2021-07-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_auto_20210720_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='position1_1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='position1_2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='position2_1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='position2_2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='position3_1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='position3_2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='position4_1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='position4_2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='position5_1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='position5_2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='position6_1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='position6_2',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
