# Generated by Django 2.2.5 on 2021-07-01 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_portal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='portal',
            new_name='volunteer_portal_ID',
        ),
    ]
